pls

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -18,61 +18,43 @@ pipeline {
                 checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: 'https://github.com/maximaxor/devopsfinal.git', credentialsId: 'git_hub']]])
             }
         }
-        stage('Setup Docker') {
+        stage('Install Docker if not present') {
             steps {
                 script {
-                    def dockerInstalled = sh(script: 'command -v docker', returnStatus: true) == 0
-                    if (!dockerInstalled) {
-                        sh """
-                        echo Docker not found, installing...
-                        curl -fsSL https://get.docker.com -o get-docker.sh
-                        sh get-docker.sh
-                        """
-                    } else {
-                        echo "Docker is already installed"
-                    }
-                    // Adding current user to Docker group
-                    sh 'sudo usermod -aG docker $(whoami)'
+                    // Check if Docker is installed and install it if not
+                    sh '''
+                        if ! command -v docker &> /dev/null
+                        then
+                            echo "Docker not found, installing..."
+                            curl -fsSL https://get.docker.com -o get-docker.sh
+                            sh get-docker.sh
+                            sudo usermod -aG docker $(whoami)
+                        else
+                            echo "Docker is already installed"
+                        fi
+                    '''
                 }
             }
         }
-        stage('Setup Dockerv2') {
+         stage('Install Kubectl') {
             steps {
                 script {
-                    sh 'ps aux | grep dockerd'
-                    sh 'docker version || (sudo dockerd & sleep 10)'
-                    sh 'sudo usermod -aG docker $(whoami)'
-                    sh 'ls -l /var/run/docker.sock'
-                    sh 'docker info'
+                    sh '''
+                        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+                        chmod +x kubectl
+                        mv kubectl /usr/local/bin/
+                    '''
                 }
             }
         }
         stage('Set up Docker Buildx') {
             steps {
                 script {
-                    sh 'docker version'
                     sh 'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes'
-                    
-                    // Install Docker Buildx
-                    sh '''
-                        mkdir -p /usr/lib/docker/cli-plugins/ && \
-                        curl -SL https://github.com/docker/buildx/releases/latest/download/buildx-$(uname -s)-$(uname -m) -o /usr/lib/docker/cli-plugins/docker-buildx && \
-                        chmod +x /usr/lib/docker/cli-plugins/docker-buildx
-                    '''
-                    
-                    def uniqueId = sh(script: 'echo $(date +%s%N | md5sum | head -c 20)', returnStdout: true).trim()
-                    def buildxAvailable = sh(script: 'docker buildx version', returnStatus: true) == 0
-                    
-                    if (buildxAvailable) {
-                        sh "docker buildx create --name builder-${uniqueId}"
-                        sh "docker buildx use builder-${uniqueId}"
-                    } else {
-                        echo "Docker buildx is not available. Please ensure you're using Docker 19.03 or later with experimental features enabled."
-                    }
+                    sh 'docker buildx create --use --name builder-$(uuidgen)'
                 }
             }
         }
-
         stage('Login to DockerHub') {
             steps {
                 script {
@@ -108,9 +90,7 @@ pipeline {
             steps {
                 container('python-test') {
                     script {
-                        sh '''
-                            pytest
-                        '''
+                        sh 'pytest'
                     }
                 }
             }
@@ -118,7 +98,7 @@ pipeline {
         stage('Push Images to Docker Hub') {
             steps {
                 script {
-                    def services = ['license-registry', 'node-app', 'image-processor', 'frontend', 'orchestrator', 'api-gateway', 'mongodb']
+                    def services = ['license-registry', 'node-app', 'image-processor', 'frontend', 'orchestrator', 'api-gateway', 'mongo-db']
                     withCredentials([usernamePassword(credentialsId: 'docker_hub', passwordVariable: 'DOCKER_HUB_TOKEN', usernameVariable: 'DOCKER_HUB_USERNAME')]) {
                         sh "docker login -u \$DOCKER_HUB_USERNAME -p \$DOCKER_HUB_TOKEN"
                         services.each { service ->
